/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 roll.gltf 
Author: TAIGA-ZOE (https://sketchfab.com/TAIGA-ZOE)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/da-vinci-code-cryptex-24d959226be84c31a1c54485bd49fcb5
Title: Da Vinci Code Cryptex
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { useLoader } from "@react-three/fiber";
import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader.js";

export default function Model(props) {
  const gltf = useLoader(GLTFLoader, "/roll/roll.gltf");
  return <primitive object={gltf.scene} scale={1} />;
}

useGLTF.preload("/roll.gltf");
