/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 plane.gltf 
Author: Darren McNerney 3D (https://sketchfab.com/DarrenMcnerney3D)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/spaceship-70e786969e70447c86bc4168df8ccbcd
Title: Spaceship
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { scene } = useGLTF("./plane/plane.gltf");
  return <primitive object={scene} {...props} />;
}

useGLTF.preload("/plane.gltf");
